export default {
    SET_EDIT_FORM_VALUES: 'SET_EDIT_FORM_VALUES',
    SET_EDIT_FORM_MODAL_VISIBILITY: 'SET_EDIT_FORM_MODAL_VISIBILITY',
    RESET_EDIT_FORM_REDUCER: 'RESET_EDIT_FORM_REDUCER',
    SET_EDIT_FORM_FETCH_STATUS: 'SET_EDIT_FORM_FETCH_STATUS',
}
