export default {
    SET_PROFILES: 'SET_PROFILES',
    ADD_PROFILE: 'ADD_PROFILE',
    SET_PROFILES_FETCH_STATUS: 'SET_PROFILES_FETCH_STATUS',
    SET_PROFILES_HAS_MORE: 'SET_PROFILES_HAS_MORE',
    RESET_PROFILES_REDUCER: 'RESET_PROFILES_REDUCER',
}
